server {
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/javascript;

    server_name 51.20.37.252;

    client_max_body_size 4G;
    types_hash_max_size 4096;

    access_log /home/anbu/MY_PROJECT/stock_inventory/logs/nginx-access.log;
    error_log /home/anbu/MY_PROJECT/stock_inventory/logs/nginx-error.log;

    location /static/ {
        alias   /home/anbu/MY_PROJECT/stock_inventory/static/;
    }

    location /media/ {
        alias   /home/anbu/MY_PROJECT/stock_inventory/media/;
    }

    # Error pages
    error_page 500 502 503 504 /500.html;
    location = /500.html {
        root /home/anbu/MY_PROJECT/stock_inventory/src/templates;
    }

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_request_buffering off;
        proxy_buffering off;


	if (!-f $request_filename) {
            proxy_pass http://unix:/home/anbu/MY_PROJECT/stock_inventory/prod/run/gunicorn.sock;
            break;
        }
    }
}
